### PR TITLE
fix issues with const

### PR DESCRIPTION
**Pull request by mikey0000**

### CODE REVIEW

**Review by qrioniclabs — APPROVED** [review]
Thanks so much! Can you explain why it is necessary to put "CONF_DB" in .const while the other configuration parameters can remain here? Thanks!

**Comment by mikey0000** [comment]
CONF_DB doesn't exist in home assistant so you need to define your own. They are only consts so defining your own is fine.

18/02/2023 7:12:48 am qrionic labs ***@***.***>:

**Comment by qrioniclabs** [comment]
Ah, I get it. So everything in https://github.com/home-assistant/core/blob/dev/homeassistant/const.py can be used by other (custom) components and it was just a coincidence that 3 out of 4 parameters I needed were already declared there. Again, thanks for your help!

**Comment by mikey0000** [comment]
Yup exactly that

18/02/2023 7:24:35 am qrionic labs ***@***.***>:

**Pull request merged**
